export const posts = [
	{
		slug: 'the-second-education',
		title: 'The Second Education',
		series: 'Zero Coordinates',
		seriesColor: 'gold',
		date: '2026-03-01',
		excerpt: 'A map of the operating system that surfaces whenever someone builds in conditions where inherited frameworks have already failed them.',
		file: 'ZC_Post1_The_Second_Education',
	},
	{
		slug: 'getting-arrested-or-killed',
		title: 'Getting Arrested or Killed',
		series: 'Zero Coordinates',
		seriesColor: 'gold',
		date: '2026-03-05',
		excerpt: 'Three men. Three centuries. Three completely different environments. Same ten commandments.',
		file: 'ZC_Post2_Getting_Arrested_or_Killed',
	},
	{
		slug: 'avoiding-insanity',
		title: 'Avoiding Insanity',
		series: 'Zero Coordinates',
		seriesColor: 'gold',
		date: '2026-03-10',
		excerpt: 'There are two kinds of insanity available to a man living outside conventional frameworks. Childers was reporting from the field on both.',
		file: 'ZC_Post3_Avoiding_Insanity',
	},
	{
		slug: 'burnout',
		title: 'Burnout',
		series: 'Zero Coordinates',
		seriesColor: 'gold',
		date: '2026-03-15',
		excerpt: 'The engine without a governor doesn\'t ask permission. It doesn\'t negotiate with exhaustion. Until it doesn\'t.',
		file: 'ZC_Post4_Burnout',
	},
	{
		slug: 'the-ignition',
		title: 'The Ignition — Forging a Full-Stack Developer in a Cambodian Crucible',
		series: 'The Build',
		seriesColor: 'ember',
		date: '2025-11-18',
		excerpt: 'Three months ago, my coding knowledge was zero. Today I\'ve engineered and deployed over fifty full-stack applications.',
		file: 'Medium_Post1_The_Ignition',
	},
];
